### PR TITLE
Fixed depracated usage of $position

### PR DESCRIPTION
**Pull request by vmanjunath**
In stead of `$position` now use `$uibPosition`.

### CODE REVIEW

**Comment by roraback** [comment]
:+1: 

Thanks, @vmanjunath, I was about to submit a similar pull request. @dnasir: This timepicker is great, but it breaks once you update Angular Bootstrap (as of Angular 0.14.0, released on 10/9/15). See documentation in the migration guide at https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes#position if you haven't seen the latest version of Bootstrap.

Also, I noticed in my project that line #192, where the 'target' variable is assigned, that even though there's no CSS animation/transition on our timepicker `<li>` elements, we're now getting a `.active-add` class a moment *before* `.active` is applied to the element. As such, we get a JS error on the first open of the timepicker at line 193 (it's looking for `.active`  on line 192, but the active element only has the `.active-add` class—which means that the target variable gets assigned a null value). I fixed it with an `or` statement when we assign the 'target' variable on line 192 to ensure it gets a value and won't throw an error on the following line

```javascript
var target = scope.timepicker.element[0].querySelector('.active-add') || scope.timepicker.element[0].querySelector('.active');
```

@vmanjunath, are you seeing the same JS error in your project when you first open a timepicker? "Uncaught TypeError: Cannot read property 'parentNode' of null" from line 193?

**Comment by dnasir** [comment]
Hi. Thanks for your contribution. I'll have a look at it and will merge soon. I've been quite busy lately.

**Comment by kroraback-fo** [comment]
Thanks! I'm looking forward to seeing update!

**Comment by roraback** [comment]
Great! I'm looking forward to seeing the update!

**Comment by dnasir** [comment]
This has now been fixed in the latest version.

**Pull request closed without merging**
